---
all:
  children:
    cisco_switches:
      hosts:
        SW-CORE-01:
          ansible_host: 192.168.100.11
          device_model: Cisco Catalyst 9300-48P
        SW-DIST-01:
          ansible_host: 192.168.100.12
          device_model: Cisco Catalyst 3850-48T
        SW-ACC-01:
          ansible_host: 192.168.100.13
          device_model: Cisco Catalyst 2960X-48FPS-L
        SW-ACC-02:
          ansible_host: 192.168.100.14
          device_model: Cisco Catalyst 9200L-24P-4G
